### ISSUE TITLE
`--red` makes the color blink

### ISSUE THREAD

**Issue by math2001** [facelessuser/ColorHelper#88]
## Description

An image is worth much more in this case:

![temp gif](https://cloud.githubusercontent.com/assets/15224242/23846923/045c81b8-0824-11e7-9081-39a55cfba928.gif)

As you can, it gives this "blinking" effect, which keeps catching my eyes, and... well, it's harder to focus.

*it removes the phantom and re-adds it with a delay, that's all*

> For bugs and support questions:

After a few tries, it seems that it's the *prefix* `--red` that creates this. Didn't find any other yet. The color doesn't change anything (you can change it, it keeps blinking)

Didn't find any error in the console

## Plugins

Because you've done such an awesome job, I reverted to a fresh state and installed PC and color helper *only*, and tried: it still blinks.

## Support Info

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.4.2
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

*Note: how about using a popup for instead of the popup, like on the [Boxy](https://github.com/ihodev/sublime-boxy/pull/151)*

## Steps to Reproduce Issue

Type in `--red: ` 😄 and a color. Copy/paste: 

```css
html {
   --red: #f00;
   --blue: #0f0
}
```

**Comment by facelessuser** [comment]
I'm getting a feeling this has nothing to do with ColorHelper.

If I enter this:

```css
html {
   --blue: #0f0;
   --red: #f00;
   --red: #f00;
   --green: #f00;
}
```

And then type something below it.

```css
html {
   --blue: #0f0;
   --red: #f00;
   --red: #f00;
   --green: #f00;
}

Some text
```

I can see `--red: #f00;` get refreshed over and over while typing.
But I don't see `--green: #f00;` refresh.

I don't look for `--red`, and I definitely don't do anything special for `red` vs `green`.  So I am hesitant to call this a ColorHelper bug at this time.  I will investigate further to be sure, but this is looking like something out of my control.
